## Hugoのコンテンツテンプレートとなるディレクトリパス
#archetypeDir = ""
## HugoがHugoPipesで使用されるアセットファイルを見つけるディレクトリパス
#AssetDir = ""
## 公開Page ルートへのホスト名（およびパス）
baseURL = "https://macrotechjp-oss.github.io/flutter-master-docs"
## 相対URLを絶対URLに変換できるかどうか(デフォルトは出来ない)
canonifyurls = true
## 言語インジケーターのないコンテンツのデフォルト言語
defaultContentLanguage = "en"
## デフォルトのコンテンツ言語をサブディレクトリにレンダリング
defaultContentLanguageInSubdir= false
## 翻訳が欠落している場合は、デフォルト値または空の文字列の代わりにプレースホルダーを表示
enableMissingTranslationPlaceholders = false
## trueの場合、コンテンツ内の中国語/日本語/韓国語を自動検出する
hasCJKLanguage = true
## サイトの言語コード
languageCode = "ja"
## Hugoが最終的な静的サイトを書き込むディレクトリパス
publishDir = "docs"
## ウェブサイト名
title = "Flutter Master Docs"
## 使用するテーマ
theme = "hugo-theme-techdoc"

[blackfriday]
    hrefTargetBlank = true

[params]
    # Source Code repository section
    # description = "put your description"
    github_repository = "https://github.com/MacrotechJP-OSS/flutter-master-docs"
    version = "0.0.0"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/MacrotechJP-OSS/flutter-master-docs"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Hugo Techdoc Theme"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = "linear-gradient(to right,#0693e3,#00dcff)"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
        "start-development"
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = true
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = "7W4SAN4PLK"
    algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.blackFriday]
        hrefTargetBlank = true
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Overviews"
        url = "/overviews"
        weight = 2

    [[menu.main]]
        name = "Functions"
        parent = "Overviews"
        url = "/overviews/functions"
        weight = 3

    [[menu.main]]
        name = "Architectures"
        parent = "Overviews"
        url = "/overviews/architectures"
        weight = 4

    [[menu.main]]
        name = "Programming"
        parent = "Overviews"
        url = "/overviews/programming"
        weight = 5

    [[menu.main]]
        name = "Test"
        parent = "Overviews"
        url = "/overviews/test"
        weight = 6

    [[menu.main]]
        name = "Deploy"
        parent = "Overviews"
        url = "/overviews/deploy"
        weight = 7

    [[menu.main]]
        name = "Operation"
        parent = "Overviews"
        url = "/overviews/operation"
        weight = 8

    [[menu.main]]
        name = "Start Development"
        url = "/start-development"
        weight = 9

    [[menu.main]]
        name = "Flutter Master"
        parent = "Start Development"
        url = "/start-development/flutter-master"
        weight = 10

    [[menu.main]]
        name = "Docs Site"
        parent = "Start Development"
        url = "/start-development/docs-site"
        weight = 11